### PR TITLE
Enable Http Invoker

### PR DESCRIPTION
**Pull request by pragnagopa**
Related issue #4970

### CODE REVIEW

**Comment by pragnagopa** [comment]
@paulbatum / @fabiocav - final part! please review.

**Comment by pragnagopa** [comment]
@brettsam - this is PR is to enable http invoker. Follow up to host PR: https://github.com/Azure/azure-functions-host/pull/5028.  Please review.

**Comment by fabiocav** [comment]
@pragnagopa this is the set of changes on top of what was recently merged into dev, correct? If so, can you please re-target the PR against the host repo?

**Comment by pragnagopa** [comment]
This is follow up PR to the host PR : https://github.com/Azure/azure-functions-host/pull/5028 which is has the implementation of the Http Worker. PR#https://github.com/Azure/azure-functions-host/pull/5028 is agaist host repo, rebased on dev

**Pull request merged**
